version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.1

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Deploy to Vercel
          command: >
            vercel --prod 
            --token=$VERCEL_TOKEN 
            --org-id=$VERCEL_ORG_ID 
            --project-id=$VERCEL_PROJECT_ID

workflows:
  deploy:
    jobs:
      - build-and-deploy