version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.1

jobs:
  build-and-deploy:
    executor: node-executor
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Pull Vercel project settings
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - run:
          name: Build project
          command: npm run build

      - run:
          name: Deploy to Vercel
          command: >
            vercel deploy 
            --prod 
            --token=$VERCEL_TOKEN 
            --yes

workflows:
  deploy:
    jobs:
      - build-and-deploy
