version: 2.1

executors:
  node-machine:
    machine:
      image: ubuntu-2204:current
    resource_class: medium  # can also use large if needed

jobs:
  build-and-deploy:
    executor: node-machine
    steps:
      - checkout

      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs

      - run:
          name: Install dependencies
          command: npm ci

      - run:
          name: Run tests
          command: npm test

      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      - run:
          name: Pull Vercel project settings
          command: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - run:
          name: Build project
          command: npm run build

      - run:
          name: Deploy to Vercel
          command: vercel deploy --prod --yes --token=$VERCEL_TOKEN

workflows:
  deploy:
    jobs:
      - build-and-deploy
